/**
    This script assumes the following:
    *   The DATABASE FlightManagement already exists (if not then create it manually before running this script)

    Everything else will be created.
*/
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Reservation;
DROP TABLE IF EXISTS Flight;
DROP TABLE IF EXISTS Airport;

DROP TABLE IF EXISTS "User";
DROP TABLE IF EXISTS "Employee";
DROP TABLE IF EXISTS "Customer";
DROP TABLE IF EXISTS "Reservation";
DROP TABLE IF EXISTS "Flight";
DROP TABLE IF EXISTS "Airport";

CREATE Table "User" (
    "UserName"    varchar(30)    NOT NULL    PRIMARY KEY,
    "PasswordHash"  varchar(256) NOT NULL
);

CREATE table "Employee" (
    "UserName" varchar(30)  NOT NULL,
    "EmployeeID" int		NOT NULL			generated by default as identity (start with 1 increment by 1),
    CONSTRAINT UserName_FK FOREIGN KEY ("UserName") REFERENCES "User"("UserName")
);

CREATE table "Customer" (
    "UserName" varchar(30)  NOT NULL,
    "CustomerID" int		NOT NULL UNIQUE			generated by default as identity (start with 1 increment by 1),
    CONSTRAINT UserName_FK FOREIGN KEY ("UserName") REFERENCES "User"("UserName")
);

CREATE TABLE "Airport"(
    "AirportCode" varchar(3)   NOT NULL,
    "AirportName" varchar(75)  NOT NULL,
    "AirportCity"  varchar(75) NOT NULL,
    "AirportState"  char(2)    NOT NULL,
    CONSTRAINT Airport_PK PRIMARY KEY ("AirportCode")
);

CREATE table "Flight" (
    "FlightID" int		 NOT NULL			generated by default as identity (restart with 1 increment by 1),
    "DepartureDate" date NOT NULL,
    "DepartureTime" time NOT NULL,
    "ArrivalDate" date NOT NULL,
    "ArrivalTime" time NOT NULL, 
    "DepartureAirport"   varchar(3),
    "ArrivalAirport"     varchar(3),
    "NumSeats"  int      NOT NULL,
    CONSTRAINT Flight_PK PRIMARY KEY ("FlightID"),
    CONSTRAINT DepartureAirport_FK FOREIGN KEY ("DepartureAirport") REFERENCES "Airport"("AirportCode"),
    CONSTRAINT ArrivalAirport_FK FOREIGN KEY ("ArrivalAirport") REFERENCES "Airport"("AirportCode")
);

CREATE table "Reservation" (
    "ReservationID" int		NOT NULL			generated by default as identity (start with 1 increment by 1),
    "FlightID"  int NOT NULL,
    "CustomerID" int NOT NULL,
    CONSTRAINT ReservationID_PK PRIMARY KEY ("ReservationID"),
    CONSTRAINT FlightID_FK FOREIGN KEY ("FlightID") REFERENCES "Flight"("FlightID"),
    
);